anoncreds/Cargo.toml
@andrewwhitehead I am not sure why it was a dependency, but if we have to keep it for some reason we can of course keep it in.
Signed-off-by: blu3beri <berend@animo.id>
=> add comment about openssl dependency

anoncreds/src/data_types/anoncreds/rev_reg_def.rs, anoncreds/src/data_types/anoncreds/schema.rs, anoncreds/src/ffi/schema.rs, anoncreds/src/services/issuer.rs, anoncreds/tests/anoncreds_demos.rs
- Dependent #25 and #27
Removes the seq_no internally (quite a small change)
closes #11 
Work funded by Government of Ontario.
=> Remove seq no

anoncreds/src/data_types/anoncreds/schema.rs, anoncreds/src/ffi/schema.rs, anoncreds/src/services/issuer.rs, anoncreds/src/services/prover.rs, anoncreds/src/services/types.rs, anoncreds/src/services/verifier.rs, anoncreds/tests/anoncreds_demos.rs
Dependent on #23, #27 and #30
- Removes the ver from the schema
- Rename attrNames to attr_names
- remove internal SchemaV1 enum wrapper
closes #10 
=> Update schema data model

anoncreds/src/data_types/anoncreds/cred_def.rs, anoncreds/src/ffi/cred_def.rs, anoncreds/src/services/issuer.rs, anoncreds/src/services/prover.rs, anoncreds/src/services/types.rs, anoncreds/src/services/verifier.rs, anoncreds/tests/utils/anoncreds.rs
Dependent upon #23, #27, #30, #31
- Remove enum wrapper around the cred def
- Remove V1 suffix after the cred def
- Removes now useless get_attribute function in the FFI layer
I will leave the revocation stuff for now. @whalelephant Feel free to pick this up (removing the V1 suffix after the structures.)
=> Remove the V1 suffix from the cred def

.github/workflows/build.yml, .gitignore, Cargo.toml, Cross.toml
Depends on #43 
closes #45 
closes #46 
- I had to patch openssl-src-rs, nothing functional, https://github.com/alexcrichton/openssl-src-rs/compare/release/111...blu3beri:openssl-src-rs:release/111 as it did not provide a build script for the target `aarch64-apple-ios-sim`. Since they do not accept non-security fixes for this branch we can not get this upstream, unless we depend upon openssl 3.
=> build: Add build for ios and android

.gitignore, anoncreds/Cargo.toml, anoncreds/src/data_types/anoncreds/rev_reg.rs, anoncreds/src/data_types/anoncreds/rev_reg_def.rs, anoncreds/src/ffi/credential.rs, anoncreds/src/ffi/revocation.rs, anoncreds/src/services/prover.rs, anoncreds/src/services/types.rs, anoncreds/src/services/verifier.rs, anoncreds/tests/anoncreds_demos.rs
This is the first PR introducing RevocationList model outlined in https://github.com/hyperledger/anoncreds-spec/issues/108 and #24.
- introduce `RevocationList` struct with serde to match outlined json, with tests
- update `create_or_update_revocation_state` function for prover and FFI. This now takes in either 1 `RevocationList` to create or optionally an old one, does a comparison and update the revocation state.
- initial end to end test in `anoncreds_demo`
Additional documentation is added to highlight the unchecked interval, which I am looking into for #36 and #41
=> Revocation List Model

anoncreds/src/data_types/anoncreds/rev_reg.rs, anoncreds/src/data_types/anoncreds/rev_reg_def.rs, anoncreds/src/ffi/credential.rs, anoncreds/src/ffi/revocation.rs, anoncreds/src/services/issuer.rs, anoncreds/src/services/prover.rs, anoncreds/src/services/types.rs, anoncreds/src/services/verifier.rs, anoncreds/tests/anoncreds_demos.rs
closes #22 
Where it was required, e.g. we pass it to Ursa, I used `ISSUANCE_BY_DEFAULT` which is a 0 or true.
@whalelephant could you also give this a review with regards to any revocation changes, I am not too familiar with the exact internals so just to be safe.
- removed the revocation registry config type
- removed V1 wrapper around revocation objects
- removed issuance by default reference
=> update revocation registry definition

.github/workflows/build.yml, include/libanoncreds.h, src/ffi/credential.rs, src/ffi/macros.rs, src/ffi/presentation.rs, src/ffi/revocation.rs, tests/utils/mock.rs, wrappers/javascript/nodejs/src/NodeJSAnoncreds.ts, wrappers/javascript/nodejs/src/ffi/primitives.ts, wrappers/javascript/nodejs/src/ffi/serialize.ts, wrappers/javascript/nodejs/src/ffi/structures.ts, wrappers/javascript/nodejs/src/library/bindings.ts, wrappers/javascript/nodejs/test/bindings.test.ts, wrappers/javascript/react-native/src/ReactNativeAnoncreds.ts, wrappers/javascript/react-native/src/library/NativeBindings.ts, wrappers/javascript/shared/src/Anoncreds.ts, wrappers/javascript/shared/src/AnoncredsObject.ts, wrappers/javascript/shared/src/api/Credential.ts, wrappers/javascript/shared/src/api/CredentialRequest.ts, wrappers/javascript/shared/src/api/CredentialRevocationConfig.ts, wrappers/javascript/shared/src/api/CredentialRevocationState.ts, wrappers/javascript/shared/src/api/Presentation.ts, wrappers/javascript/shared/src/api/RevocationRegistry.ts, wrappers/javascript/shared/src/api/RevocationRegistryDefinition.ts, wrappers/javascript/shared/src/api/RevocationRegistryDelta.ts, wrappers/javascript/shared/src/api/RevocationStatusList.ts
- added: `anoncreds_create_revocation_status_list`, `anoncreds_update_revocation_status_list` and `anoncreds_update_recovation_status_list_timestamp_only`.
- Both updates remove the object handle for the previous status list. I assumed that the this is the correct behaviour.
- Made some small changes to the JS wrapper
=> feat(ffi): updated with new methods

wrappers/javascript/anoncreds-shared/src/api/Presentation.ts, wrappers/javascript/anoncreds-shared/src/api/RevocationRegistryDefinition.ts, wrappers/javascript/anoncreds-shared/src/api/index.ts
Some minor fixes in JavaScript wrapper:
- Remove the need of passing a `Presentation` instance in `verify`, as it is an instance method and can get the handle by itself
- Expose `RevocationStatusList`
- Fix `RevocationRegistryDefinition.load` method
=> fix(js): missing export and return type

wrappers/javascript/anoncreds-react-native/src/ReactNativeAnoncreds.ts, wrappers/javascript/anoncreds-react-native/src/library/NativeBindings.ts, wrappers/javascript/anoncreds-shared/src/api/CredentialRequest.ts
Since #57, prover_did in Credential Request is optional and some parts of the wrappers have been updated accordingly. But there were some missing changes in interfaces for both Node.JS and React Native wrappers that are updated here.
Signed-off-by: Ariel Gentile <gentilester@gmail.com>
=> fix(js): proverDid optional in Credential Request

.github/workflows/build.yml, .gitignore, build-xcframework.sh, build.sh
- Build the xcframework with dynamic instead of static libraries
- used in the CI now
- Dynamic libraries and frameworks pushing to the App Store can fail if it is not setup correctly I think.
- Since I am not an iOS developer I "botched" together some of the resources about constructing a `.framework` online, but we have to push an app to the app store to see whether it is done properly. if anyone knows anyone with experience like this, help would be awesome!
- This is by no means a perfect shell script. It can be refactored later, but it does the job for now.
=> build: build xc frameworks with dylibs

wrappers/javascript/anoncreds-nodejs/src/NodeJSAnoncreds.ts, wrappers/javascript/anoncreds-nodejs/src/ffi/serialize.ts, wrappers/javascript/anoncreds-nodejs/src/ffi/structures.ts, wrappers/javascript/anoncreds-nodejs/test/bindings.test.ts, wrappers/javascript/anoncreds-react-native/cpp/anoncreds.cpp, wrappers/javascript/anoncreds-react-native/cpp/anoncreds.h, wrappers/javascript/anoncreds-react-native/src/ReactNativeAnoncreds.ts, wrappers/javascript/anoncreds-react-native/src/library/NativeBindings.ts, wrappers/javascript/anoncreds-shared/src/Anoncreds.ts, wrappers/javascript/anoncreds-shared/src/api/CredentialRevocationState.ts, wrappers/javascript/anoncreds-shared/src/api/RevocationRegistryDefinition.ts, wrappers/javascript/anoncreds-shared/src/api/RevocationStatusList.ts
there might still be some minor issues with some properties being required by CPP but can be undefined by JS. I will fix this incrementally when we test AFJ for RN with Anoncreds.
I added quite a bit of casting to avoid the `@ts-ignore`. This should be cleaned up, but can be done later. It has to be done because ref-napi, struct-napi and array-napi create some funky non-interop types. 
I would like to fix this more generic so we can copy some code between all the shared modules and do it properly.
=> fix(js): added casting and fixed RN bindings

src/ffi/credential.rs, wrappers/javascript/anoncreds-nodejs/src/NodeJSAnoncreds.ts, wrappers/javascript/anoncreds-nodejs/src/library/bindings.ts, wrappers/javascript/anoncreds-nodejs/test/api.test.ts, wrappers/javascript/anoncreds-nodejs/test/bindings.test.ts, wrappers/javascript/anoncreds-nodejs/test/utils/initialize.ts, wrappers/javascript/anoncreds-shared/src/api/CredentialRevocationConfig.ts
When attempting to create some credentials without any kind of revocation configuration, under JS I've noticed that it was not properly handling some optional parameters for creating and processing credentials:
- In `create_credential`, `revocationConfiguration` was sending a default CredRevInfoStruct, that library was not interpreting as null so it was throwing an error about missing tails file path
- Also in `create_credential`, JS wrapper was not accepting an empty  `revocationStatusList`. In addition, once solved, Rust part was throwing an 'Invalid object handle' error when trying to load the object as it was mandatory
- In `process_credential`, JS wrapper was not accepting an empty `revocationRegistryDefinition`
I'm not sure if the solutions implemented in this PR are completely …
=> fix: parameters when creating credentials without revocation

Cargo.toml
`ursa` version 0.3.6 still has dependencies on the long deprecated `failure` crate which is no longer maintained and contains well known security issues (CVE-2019-25010 and CVE-2020-25575).
fix #123
=> update `ursa` to 0.3.7

wrappers/javascript/anoncreds-react-native/cpp/HostObject.cpp, wrappers/javascript/anoncreds-react-native/cpp/anoncreds.cpp, wrappers/javascript/anoncreds-react-native/cpp/anoncreds.h, wrappers/javascript/anoncreds-react-native/cpp/include/libanoncreds.h, wrappers/javascript/anoncreds-react-native/cpp/turboModuleUtility.cpp, wrappers/javascript/anoncreds-react-native/src/ReactNativeAnoncreds.ts, wrappers/javascript/anoncreds-react-native/src/library/NativeBindings.ts
Adding the missing methods from react-native wrappers and making lots of minor fixes, mostly related to typos and outdated variable/method names.
At the moment working for a full issuance / present proof / verify proof flow without revocation (yes, also possible to issue a credential in React Native 🎉). However there is a memory leak leading to custom app crashes and variable corruption (!) when creating presentation.  Based on some debugging I did, the corrupted variables are strings in some FFI lists: it seems that strings are cleared or updated by the runtime before they are used by native library. Not sure if this makes sense, but I noticed that if I use short strings for fields like `issuerId`, `schemaId` and `credentialDefinitionId` (e.g. _'mock:uri'_) the flow works fine …
=> fix(js): missing getXXXFromJson methods and several typos

wrappers/javascript/anoncreds-nodejs/src/NodeJSAnoncreds.ts, wrappers/javascript/anoncreds-nodejs/test/api.test.ts, wrappers/javascript/anoncreds-nodejs/test/bindings.test.ts, wrappers/javascript/anoncreds-react-native/cpp/anoncreds.cpp, wrappers/javascript/anoncreds-react-native/src/ReactNativeAnoncreds.ts, wrappers/javascript/anoncreds-react-native/src/library/NativeBindings.ts, wrappers/javascript/anoncreds-shared/src/Anoncreds.ts, wrappers/javascript/anoncreds-shared/src/AnoncredsObject.ts, wrappers/javascript/anoncreds-shared/src/api/Credential.ts, wrappers/javascript/anoncreds-shared/src/api/CredentialDefinition.ts, wrappers/javascript/anoncreds-shared/src/api/CredentialDefinitionPrivate.ts, wrappers/javascript/anoncreds-shared/src/api/CredentialOffer.ts, wrappers/javascript/anoncreds-shared/src/api/CredentialRequest.ts, wrappers/javascript/anoncreds-shared/src/api/CredentialRequestMetadata.ts, wrappers/javascript/anoncreds-shared/src/api/CredentialRevocationConfig.ts, wrappers/javascript/anoncreds-shared/src/api/CredentialRevocationState.ts, wrappers/javascript/anoncreds-shared/src/api/KeyCorrectnessProof.ts, wrappers/javascript/anoncreds-shared/src/api/MasterSecret.ts, wrappers/javascript/anoncreds-shared/src/api/Presentation.ts, wrappers/javascript/anoncreds-shared/src/api/PresentationRequest.ts, wrappers/javascript/anoncreds-shared/src/api/RevocationRegistry.ts, wrappers/javascript/anoncreds-shared/src/api/RevocationRegistryDefinition.ts, wrappers/javascript/anoncreds-shared/src/api/RevocationRegistryDefinitionPrivate.ts, wrappers/javascript/anoncreds-shared/src/api/RevocationRegistryDelta.ts, wrappers/javascript/anoncreds-shared/src/api/RevocationStatusList.ts, wrappers/javascript/anoncreds-shared/src/api/Schema.ts, wrappers/javascript/anoncreds-shared/src/api/utils.ts, wrappers/javascript/anoncreds-shared/src/types.ts
This is an attempt (without doing anything revolutionary) to make JS API a bit more simple to use, avoiding the so-many conversions from JSON to string  that we found during integration with AFJ. 
For most methods that are currently receiving `AnoncredsObject` instances, now we accept also passing JSON objects. This makes the caller to not care about object instantiation and clearing handles, which is done internally. Hopefully, in a normal flow the caller will need only to care about freeing a few objects (like Credentials).
I'm not sure if I'm using the `try-finally` method correctly (I'm particularly worried about the order of execution of finally if an exception is thrown) so any comments on this approach would be appreciated. I wanted to make this process of "checking object type and …
=> refactor(js)!: use JSON objects in API instead of strings and instances

wrappers/javascript/anoncreds-react-native/cpp/anoncreds.cpp, wrappers/javascript/anoncreds-react-native/cpp/include/libanoncreds.h, wrappers/javascript/anoncreds-react-native/cpp/turboModuleUtility.cpp, wrappers/javascript/anoncreds-react-native/src/ReactNativeAnoncreds.ts, wrappers/javascript/anoncreds-react-native/src/library/NativeBindings.ts
- Fixes `XXXFromJson()` functions that were losing the input string value due to the usage of vectors
- Fixes `createPresentation` and `verifyPresentation`, that were losing strings that were passed to FFI structures, and also were not being freed after usage
- Updates some methods like `createRevocationStatusList` and `verifyPresentation` according to last API changes
=> fix(js): strings in FFI structs and JSON conversion in react native

src/data_types/cred_request.rs, src/data_types/issuer_id.rs, src/data_types/macros.rs, src/services/prover.rs, src/services/verifier.rs, src/utils/validation.rs, tests/utils/mock.rs
@genaris this should fix your issue regarding the invalid cred_def / schema identifiers.
I was wondering if anyone knows a regex to match the revocation registry definition id and the revocation registry id.
Since the new identifier checker checks if it's just a uri, we will validate incorrect schemas with a version of `3` for example. Curious to hear if we want to fix this or leave as-is.
=> fix: add support for legacy schema and cred def id

.github/workflows/build.yml, Cargo.toml
- Updated dependencies to their latest version
- Removed the dependency on openssl-src from github which should drastically
increase first build times (also on CI)
=> chore: update dependencies

src/ffi/revocation.rs, wrappers/javascript/anoncreds-nodejs/src/NodeJSAnoncreds.ts, wrappers/javascript/anoncreds-nodejs/src/library/bindings.ts, wrappers/javascript/anoncreds-nodejs/test/api.test.ts, wrappers/javascript/anoncreds-react-native/cpp/HostObject.cpp, wrappers/javascript/anoncreds-react-native/cpp/anoncreds.cpp, wrappers/javascript/anoncreds-react-native/cpp/anoncreds.h, wrappers/javascript/anoncreds-react-native/src/ReactNativeAnoncreds.ts, wrappers/javascript/anoncreds-react-native/src/library/NativeBindings.ts, wrappers/javascript/anoncreds-shared/src/Anoncreds.ts, wrappers/javascript/anoncreds-shared/src/api/Presentation.ts, wrappers/javascript/anoncreds-shared/src/api/RevocationStatusList.ts, wrappers/python/anoncreds/types.py
This add support to create a revocation status list from json in the JS wrapper. The method was already availalbe in the ffi layer as `anoncreds_revocation_list_from_json`, but I changed it to `anoncreds_revocation_status_list_from_json` as that aligns more with the rest of the naming. If we choose to call it `revocation_list` we should change it everywhere at once.
Also fixes a few small issues in the RN wrapper.
=> feat(js): revocation status list from json

wrappers/javascript/anoncreds-react-native/cpp/anoncreds.cpp
Link secret has changed from object to just a string, but this wasn't reflected in the C++ layer
=> fix(rn): link secret is string instead of object

wrappers/javascript/anoncreds-nodejs/src/NodeJSAnoncreds.ts, wrappers/javascript/anoncreds-react-native/cpp/anoncreds.cpp, wrappers/javascript/anoncreds-react-native/src/ReactNativeAnoncreds.ts, wrappers/javascript/anoncreds-react-native/src/library/NativeBindings.ts, wrappers/javascript/anoncreds-shared/src/Anoncreds.ts, wrappers/javascript/anoncreds-shared/src/api/CredentialRevocationState.ts
Fixes some inconsistencies and issues encountered when testing proving of revocable credentials. There's probably a few things that are broken in the verification / issuance as well, but I've mostly focused on the holder role now.
=> fix(js): inconsistencies in create revocation state

.github/workflows/build.yml
- Renamed `check` to `test` to reflect the cargo subcommand
- Removed `macos` from `test` to avoid unnecessary macos runs.
=> build: remove macos from check

wrappers/javascript/anoncreds-nodejs/src/NodeJSAnoncreds.ts, wrappers/javascript/anoncreds-react-native/src/ReactNativeAnoncreds.ts, wrappers/javascript/anoncreds-shared/src/api/RevocationStatusList.ts
Some things I found while digging a bit with revocation status lists in JavaScript.
Also, maybe more for a discussion or separate issue, but I find a bit odd to have both `updateTimestamp()` and `update()` methods in `RevocationStatusList` class from JS API. It could be more straightforward to just have `update()` and, if the only defined parameter is the timestamp, it can call `anoncreds.updateRevocationStatusListTimestampOnly`.
=> fix(js): revocation status list typo and optional timestamp

wrappers/javascript/anoncreds-nodejs/src/NodeJSAnoncreds.ts, wrappers/javascript/anoncreds-nodejs/test/api.test.ts, wrappers/javascript/anoncreds-shared/src/Anoncreds.ts, wrappers/javascript/anoncreds-shared/src/api/Presentation.ts
A very subtle option naming was preventing the non revoked interval overrides to get processed by Rust code: base Anoncreds interface was using `nonRevokedIntervalOverride` while NodeJS and ReactNative implementations are referring to it as `nonRevokedIntervalOverrides` (which makes more sense as it is an array of overrides).
Solves #191 and updates a bit API test to reflect the usage of this parameter.
=> fix(js): nonRevokedIntervalOverrides naming

.github/workflows/build.yml, build-xcframework.sh
Now using static libraries, which have a lower minimum iOS version suppport, does increase download and possible bundle size (last one is untested).
=> chore: lower ios compatibility

wrappers/javascript/anoncreds-react-native/android/CMakeLists.txt, wrappers/javascript/anoncreds-react-native/android/build.gradle
- Same as https://github.com/hyperledger/aries-askar/pull/142
- Additional support for Expo will be added in a seperate PR
- Based on this PR: https://github.com/hyperledger/aries-askar/commit/777ec8a40322102b08084aed3659257b646a8b8d
=> feat: react native > 0.71.x support

Cargo.toml, src/data_types/link_secret.rs, src/data_types/rev_status_list.rs, src/ffi/credential.rs, src/services/helpers.rs, src/services/prover.rs, src/services/tails.rs, src/services/types.rs, tests/anoncreds_demos.rs, tests/utils/mock.rs, wrappers/python/anoncreds/bindings.py, wrappers/python/anoncreds/types.py, wrappers/python/demo/test.py
This merges some changes to the tails file handling from indy-credx. The tempfile library is not compatible with some filesystems like on Azure (https://github.com/hyperledger/indy-shared-rs/issues/21). This removes that dependency and adds buffering to the IO operations which helps performance.
The tails file path is no longer required for the credential revocation config when issuing, this would require a JS wrapper update as well.
=> Update to anoncreds-clsignatures 0.2, update tails access

src/data_types/cred_def.rs, src/data_types/cred_request.rs, src/data_types/rev_status_list.rs, src/data_types/schema.rs, src/ffi/cred_def.rs, src/ffi/cred_offer.rs, src/ffi/revocation.rs, src/ffi/schema.rs, src/services/issuer.rs, src/services/prover.rs, src/utils/query.rs, tests/anoncreds_demos.rs, tests/multiple-credentials.rs, tests/utils/fixtures.rs, tests/utils/mock.rs, tests/utils/storage.rs
This PR is based on #226 .
Small improvements to the `services` module function signatures aiming to make it easier for native consumers to use the library.
Main goal was to get rid of `TryInto<T, Error = ValidationError>` like arguments because that prevented consumers from passing `T` as an argument (because `TryFrom<T> for T` has an `Infallible` error type).
There still are arguments like `&HashMap<&SchemaId, &Schema>` which aren't really straight-forward to fix due to the implications this has in the FFI layer (maps are constructed at runtime from FFI objects references).
Worth looking into would also be `issuer::update_revocation_status_list()` as it's fairly painful to deal with, but I believe that's really more due to the `RevocationRegistryDelta` - `RevocationStatusList` data …
=> refactor: services function signatures improvements

Cargo.toml, src/data_types/rev_reg.rs, src/data_types/rev_status_list.rs, src/services/issuer.rs, src/services/prover.rs, src/services/verifier.rs
Updates to anoncreds-clsignatures 0.2.1 and simplifies revocation registry handling.
=> Revocation registry cleanups

wrappers/javascript/anoncreds-nodejs/src/NodeJSAnoncreds.ts, wrappers/javascript/anoncreds-nodejs/src/library/bindings.ts, wrappers/javascript/anoncreds-react-native/cpp/turboModuleUtility.cpp
Not completely sure if it's the right approach (especially in react-native) but here is a simple attempt to free strings automatically in JS wrappers before returning to the caller, as discussed in https://github.com/hyperledger/anoncreds-rs/issues/236.
=> fix(js): free native strings

Cargo.toml, src/data_types/link_secret.rs, src/services/helpers.rs, src/services/prover.rs
This updates to anoncreds-clsignatures 0.2.2 to take advantage of simple conversion from the link secret to a BigNumber. I don't think there's any reason to support conversion from ClLinkSecret to LinkSecret anymore as the `build_credential_values` method is updated to use LinkSecret.
=> Simplify LinkSecret handling

wrappers/javascript/anoncreds-nodejs/package.json, wrappers/javascript/yarn.lock
Following the issue with types that appeared in https://github.com/hyperledger/aries-askar/pull/170#issuecomment-1708337866, here we update patched `ref-napi` and `ffi-napi` to embed their own types instead of using the ones from the original ones.
=> fix(js): bump patched ref-napi/ffi-napi

src/data_types/credential.rs
=> Make zeroize not used with `no-default-features`

Cargo.toml, MAINTAINERS.md, src/ffi/credential.rs, src/services/mod.rs, tests/multiple-credentials.rs
- create zeroize feature (I am suprised that using `#[cfg(feature = "zeroize")]` worked without it being a feature. Maybe it picks up the dep)
Some not-so related changes included in this PR
- change blu3beri to berendsliedrecht GitHub name
- fix cargo issues and test work without default-features
=> feat: add zeroize as a feature

src/services/verifier.rs
closes #252 
Minor bug where a value contains a "0" without having any digits behind it. 
Updated the regex to check for leading zeroes which must be followed by another digit. If this is the case, we trim the zeroes and return the leftover. If it is something like `0011212abab` it does not strip the zeroes.
https://github.com/hyperledger/aries-rfcs/tree/main/features/0592-indy-attachments#notes-on-encoding-claims
=> fix leading zero bug

.github/workflows/build.yml, .gitignore
=> do not write to .npmrc for release

src/services/issuer.rs, src/services/verifier.rs, tests/utils/fixtures.rs
=> fix minor typos in comments

wrappers/javascript/.prettierignore, wrappers/javascript/package.json
By default prettier ignores paths in .gitignore and .prettierignore, so I've removed the explicit override of ignore-path.
=> Do not apply prettier to pnpm lockfile

src/data_types/w3c/credential_attributes.rs, src/services/verifier.rs, src/services/w3c/credential_conversion.rs, src/services/w3c/helpers.rs, src/services/w3c/types.rs, src/services/w3c/verifier.rs, tests/anoncreds_demos.rs, tests/utils/mock.rs
Represent number credential values as `numbers` in W3C credential subject.
Current implementation similar to attributes encoding function. If a number can be parsed from raw value, put it as a number into a credential subject as well. 
Probably, in future, we better to change the function API to  accept some rich structure specifying value types along with values.  
Issue: https://github.com/hyperledger/anoncreds-rs/issues/297
=> Support numbers values in AnonCreds W3C VC

Cargo.lock.android, Cargo.toml, wrappers/javascript/lerna.json, wrappers/javascript/packages/anoncreds-nodejs/package.json, wrappers/javascript/packages/anoncreds-react-native/package.json, wrappers/javascript/packages/anoncreds-shared/package.json, wrappers/python/anoncreds/version.py
To release latest PR to encode numbers as numbers, and the last release went wrong
=> chore: update version to 0.2.0-dev.7

src/data_types/cred_request.rs, src/utils/validation.rs
Fixes #307 
This is more consistent with indy-credx, where a 'fully qualified' identifier is accepted, although more lax in that only a URI scheme is required.
=> Relax validation on prover_did in a credential request

src/data_types/macros.rs, src/utils/validation.rs
Fixes #312 
The regex is a bit strict, as only the CL signature type and CL_ACCUM registry type are allowed, but that seems consistent with the cred def ID validation.
=> Fix validation of legacy rev reg definition ID

wrappers/python/anoncreds/bindings.py
Without this fix, the method fails with "TypeError: expected LP_c_char instance, got int"
=> Fix library_version in python wrapper

Cargo.lock.android, Cargo.toml, docs/design/w3c/w3c-representation.md, src/ffi/w3c/credential.rs, src/services/w3c/credential_conversion.rs, tests/utils/mock.rs, wrappers/javascript/lerna.json, wrappers/javascript/packages/anoncreds-nodejs/package.json, wrappers/javascript/packages/anoncreds-nodejs/src/NodeJSAnoncreds.ts, wrappers/javascript/packages/anoncreds-nodejs/src/library/bindings.ts, wrappers/javascript/packages/anoncreds-nodejs/tests/api.test.ts, wrappers/javascript/packages/anoncreds-react-native/cpp/anoncreds.cpp, wrappers/javascript/packages/anoncreds-react-native/package.json, wrappers/javascript/packages/anoncreds-react-native/src/NativeBindings.ts, wrappers/javascript/packages/anoncreds-react-native/src/ReactNativeAnoncreds.ts, wrappers/javascript/packages/anoncreds-shared/package.json, wrappers/javascript/packages/anoncreds-shared/src/Anoncreds.ts, wrappers/javascript/packages/anoncreds-shared/src/api/Credential.ts, wrappers/javascript/packages/anoncreds-shared/src/api/W3cCredential.ts, wrappers/python/anoncreds/bindings.py, wrappers/python/anoncreds/types.py, wrappers/python/anoncreds/version.py, wrappers/python/demo/w3c_test.py
We were running into some issues when needing to transform between legacy -> w3c anoncreds as the method requires the cred_def to be passed. It seems the cred_def is only required for the issuer_id, and this PR updates it to only require a string issuer_id rather than the whole cred def. 
In our case we know the issuer_id, but we'd have to resolve the cred_def from the ledger
=> refactor: only issuer id for legacy->w3c

src/services/w3c/types.rs, tests/anoncreds_demos.rs
Related issue: https://github.com/hyperledger/anoncreds-rs/issues/321
=> Corrected building of W3C credential values passed through the FFI

src/data_types/w3c/credential.rs, src/data_types/w3c/presentation.rs, src/services/w3c/verifier.rs
=> Extra validation for w3c credentials and presentations

Cargo.lock.android, Cargo.toml, wrappers/javascript/lerna.json, wrappers/javascript/packages/anoncreds-nodejs/package.json, wrappers/javascript/packages/anoncreds-react-native/package.json, wrappers/javascript/packages/anoncreds-shared/package.json, wrappers/python/anoncreds/version.py
We've verified everything to work correclty and would like to include AnonCreds 0.2.0 in the 0.5.0 release of Credo.
=> chore: update to stable 0.2.0

wrappers/javascript/lerna.json, wrappers/javascript/packages/anoncreds-nodejs/package.json, wrappers/javascript/packages/anoncreds-react-native/package.json, wrappers/javascript/packages/anoncreds-shared/package.json
Updating version to 0.2.1 after #327. Only for the JS wrapper, as I understand we follow the same strategy as in Askar and Indy VDR. I think @TimoGlastra in #296 did already the set-up so it will be just a matter of running the workflow manually.
=> chore: update version for js wrapper

src/data_types/w3c/format.rs, src/data_types/w3c/proof.rs, src/services/w3c/verifier.rs
After checking the issue found in https://github.com/hyperledger/anoncreds-rs/pull/331 I thought: "why just don't make rustfmt happy?". So I simply ran the formatter using the version we are using in the CI.
=> style: adapt to rustfmt 1.6.0 rules

wrappers/javascript/packages/anoncreds-nodejs/package.json, wrappers/javascript/pnpm-lock.yaml
Updated `ffi-napi` dependency on JS wrapper in order to fix the incompatibility issue found with newer node.js versions. See https://github.com/nodejs/node/issues/52240#issuecomment-2040598178.
=> fix(js): update ffi-napi

wrappers/javascript/packages/anoncreds-react-native/android/build.gradle
This PR updates the react-native wrapper to get the minSdkVersion from the project config or fallback to the current hardcoded version. @TimoGlastra @berendsliedrecht
=> chore: update minSdkVersion to get the project version or fallback to 21

.github/workflows/build.yml, wrappers/javascript/lerna.json, wrappers/javascript/packages/anoncreds-nodejs/package.json, wrappers/javascript/packages/anoncreds-nodejs/tsconfig.json, wrappers/javascript/packages/anoncreds-react-native-example/package.json, wrappers/javascript/packages/anoncreds-react-native/package.json, wrappers/javascript/packages/anoncreds-react-native/tsconfig.json, wrappers/javascript/packages/anoncreds-shared/package.json, wrappers/javascript/pnpm-lock.yaml
Update version so we can release https://github.com/hyperledger/anoncreds-rs/pull/338
=> chore(js): update version to 0.2.3

.github/workflows/build.yml
actions/upload-artifact and actions/download-artifact have been deprecated and need updated.
https://github.blog/changelog/2024-04-16-deprecation-notice-v3-of-the-artifact-actions/
=> chore: update actions

Cargo.toml, wrappers/python/anoncreds/version.py
Just a version bump prior to triggering a new release. Although we still have the issue of creating Python wrapper (#365), I think we can create a new release to publish mobile binaries required by JavaScript wrapper.
=> chore: v0.2.2
