.github/workflows/build.yml
Cargo.toml

Updated to correct openssl-src repo

---

src/ffi/cred_req.rs
src/services/prover.rs
wrappers/python/README.md
wrappers/python/anoncreds/__init__.py
wrappers/python/anoncreds/bindings.py
wrappers/python/anoncreds/error.py
wrappers/python/anoncreds/types.py
wrappers/python/anoncreds/version.py
wrappers/python/demo/test.py
wrappers/python/indy_credx/version.py
wrappers/python/setup.py

Fixed the bindings from credx to anoncreds and updated the api.
Still some issues with the tests, mostly regarding revocation, as that is not yet finished from the ffi side.

feat(python): bindings working

---

src/data_types/rev_reg.rs
src/ffi/presentation.rs
src/services/verifier.rs
tests/anoncreds_demos.rs
tests/utils/mock.rs

fix: remove requirement for rev reg in verify function

---

Cargo.toml
wrappers/javascript/anoncreds-nodejs/package.json
wrappers/javascript/anoncreds-nodejs/test/bindings.test.ts
wrappers/javascript/anoncreds-react-native/README.md
wrappers/javascript/anoncreds-react-native/package.json
wrappers/javascript/anoncreds-shared/package.json
wrappers/javascript/lerna.json
wrappers/python/README.md

Signed-off-by: Timo Glastra <timo@animo.id>

build: small issues with release

---

Cargo.toml
wrappers/javascript/anoncreds-nodejs/package.json
wrappers/javascript/anoncreds-react-native/package.json
wrappers/javascript/anoncreds-shared/package.json
wrappers/javascript/lerna.json

chore: update versions

---

.github/workflows/build.yml
wrappers/javascript/anoncreds-nodejs/test/bindings.test.ts

build: updated version in the test

---

build-xcframework.sh

build(ios): change the id so it works in production

---

wrappers/javascript/anoncreds-shared/src/api/Credential.ts
wrappers/javascript/anoncreds-shared/src/api/RevocationRegistryDefinition.ts

Some API builder classes were missing latest updates after spec changes.

fix(js): remove originDid and add revocationStatusList

---

wrappers/javascript/anoncreds-shared/src/api/Presentation.ts

They are optional but in CredentialEntry (used in Presentation) are marked as mandatory

fix(js): CredentialEntry optional parameters

---

Cargo.toml
build-xcframework.sh
wrappers/javascript/anoncreds-nodejs/package.json
wrappers/javascript/anoncreds-nodejs/test/bindings.test.ts
wrappers/javascript/anoncreds-react-native/package.json
wrappers/javascript/anoncreds-shared/package.json
wrappers/javascript/lerna.json
wrappers/python/anoncreds/version.py

Signed-off-by: Timo Glastra <timo@animo.id>

chore: update version to 0.1.0-dev.5

---

wrappers/javascript/anoncreds-react-native/cpp/anoncreds.cpp

fix(js): fixed some typos for RN

---

wrappers/javascript/anoncreds-react-native/android/cpp-adapter.cpp
wrappers/javascript/anoncreds-react-native/cpp/HostObject.cpp
wrappers/javascript/anoncreds-react-native/cpp/HostObject.h
wrappers/javascript/anoncreds-react-native/cpp/anoncreds.cpp
wrappers/javascript/anoncreds-react-native/cpp/turboModuleUtility.cpp
wrappers/javascript/anoncreds-react-native/cpp/turboModuleUtility.h
wrappers/javascript/anoncreds-react-native/ios/Anoncreds.mm

fix(js): allow multiple turbo modules to be registered

---

Cargo.toml
wrappers/javascript/anoncreds-nodejs/package.json
wrappers/javascript/anoncreds-nodejs/test/bindings.test.ts
wrappers/javascript/anoncreds-react-native/package.json
wrappers/javascript/anoncreds-shared/package.json
wrappers/javascript/lerna.json

chore: update version

---

wrappers/javascript/anoncreds-react-native/cpp/HostObject.cpp
wrappers/javascript/anoncreds-react-native/cpp/turboModuleUtility.h

fix(js): fixed minor typos

---

wrappers/javascript/anoncreds-react-native/cpp/anoncreds.cpp

fix(js): remove credentialDefinitionId

---

include/libanoncreds.h
src/data_types/cred_request.rs
src/ffi/cred_req.rs
src/services/issuer.rs
src/services/prover.rs
src/utils/query.rs
tests/anoncreds_demos.rs
tests/utils/mock.rs
wrappers/javascript/anoncreds-nodejs/src/NodeJSAnoncreds.ts
wrappers/javascript/anoncreds-nodejs/src/library/bindings.ts
wrappers/javascript/anoncreds-nodejs/test/api.test.ts
wrappers/javascript/anoncreds-nodejs/test/bindings.test.ts
wrappers/javascript/anoncreds-react-native/cpp/HostObject.cpp
wrappers/javascript/anoncreds-react-native/cpp/anoncreds.cpp
wrappers/javascript/anoncreds-react-native/cpp/include/libanoncreds.h
wrappers/javascript/anoncreds-react-native/src/ReactNativeAnoncreds.ts
wrappers/javascript/anoncreds-react-native/src/library/NativeBindings.ts
wrappers/javascript/anoncreds-shared/src/Anoncreds.ts
wrappers/javascript/anoncreds-shared/src/api/CredentialRequest.ts

add required entropy instead of optional prover_did

---

wrappers/javascript/anoncreds-react-native/cpp/HostObject.cpp
wrappers/javascript/anoncreds-react-native/cpp/anoncreds.cpp
wrappers/javascript/anoncreds-react-native/cpp/anoncreds.h
wrappers/javascript/anoncreds-react-native/cpp/turboModuleUtility.cpp

fix(js): removed uint32_t createReturnValue

---

tests/anoncreds_demos.rs
tests/utils/fixtures.rs
tests/utils/mod.rs

test(demo): enabled more tests

---

src/data_types/cred_def.rs
src/data_types/rev_reg_def.rs

fix: validate issuer id on some objects

---

.github/workflows/build.yml

This should resolve the deprecation warnings in actions.

chore(ci): Update to upload-artifact v3

---

wrappers/python/pyproject.toml

closes #154 
@dbluhm any chance you can review this? I followed some guides, and the demo is working, but python setup still remains a small mystery to me :).

chore(python): added pyproject.toml

---

.github/workflows/build.yml
build-universal.sh

Co-authored-by: blu3beri <blu3beri@proton.me>
Co-authored-by: Vickysomtee <victor@animo.id>

build(python): added CI/CD

---

.github/workflows/build.yml

build: remove duplicate name key

---

build-universal.sh

chore: update name in build-universal

---

wrappers/javascript/anoncreds-nodejs/package.json
wrappers/javascript/yarn.lock

- In response to: https://github.com/hyperledger/anoncreds-rs/security/dependabot/1

chore: regenerated yarn lock file

---

.github/workflows/build.yml
src/ffi/cred_def.rs
src/ffi/presentation.rs
src/services/issuer.rs
src/services/verifier.rs

fix(build): use cross for lower glibc compatibility

---

Cargo.toml
wrappers/javascript/anoncreds-nodejs/package.json
wrappers/javascript/anoncreds-react-native/package.json
wrappers/javascript/anoncreds-shared/package.json
wrappers/javascript/lerna.json
wrappers/python/anoncreds/__init__.py
wrappers/python/anoncreds/bindings.py
wrappers/python/anoncreds/types.py
wrappers/python/anoncreds/version.py
wrappers/python/demo/test.py

- fix(python): link secret is string
closes #194

fix(python): link secret

---

wrappers/javascript/anoncreds-nodejs/package.json
wrappers/javascript/anoncreds-nodejs/scripts/platform.js

fix(nodejs): compatible with Windows builds

---

.github/workflows/build.yml
wrappers/javascript/.gitignore

build(python): add library

---

wrappers/javascript/anoncreds-react-native/android/build.gradle

fix: small typo in the build.gradle

---

.github/workflows/build.yml

build(python): use correct matrix

---

.github/workflows/build.yml
Cross.toml

- Using custom images for building with lower Android support
- If this fully works the same will be done with https://github.com/hyperledger/aries-askar and https://github.com/hyperledger/indy-vdr

build(android): use custom cross images

---

wrappers/javascript/anoncreds-react-native/android/CMakeLists.txt
wrappers/javascript/anoncreds-react-native/android/build.gradle

Tested with:
RN 66 - JSC 
RN 66 - Hermes
RN 71 - JSC
RN 71 - Hermes

fix(rn): android works with JSC and Hermes

---

Cargo.toml
wrappers/javascript/anoncreds-nodejs/package.json
wrappers/javascript/anoncreds-react-native/package.json
wrappers/javascript/anoncreds-shared/package.json
wrappers/javascript/lerna.json
wrappers/python/anoncreds/version.py

chore: update to stable release

---

Cargo.toml
wrappers/javascript/anoncreds-nodejs/README.md
wrappers/javascript/anoncreds-nodejs/package.json
wrappers/javascript/anoncreds-react-native/package.json
wrappers/javascript/anoncreds-shared/package.json
wrappers/javascript/lerna.json
wrappers/python/anoncreds/version.py

As discussed in today's AFJ call, updating version to a new dev one.

chore: update version to 0.2.0-dev.1

---

wrappers/javascript/lerna.json
wrappers/javascript/package.json
wrappers/javascript/packages/anoncreds-nodejs/package.json
wrappers/javascript/pnpm-lock.yaml

lock lerna to 7.2.0

---

wrappers/javascript/packages/anoncreds-nodejs/scripts/install.js

fix js install script issue with platform

---

Cargo.toml
wrappers/javascript/lerna.json
wrappers/javascript/packages/anoncreds-nodejs/package.json
wrappers/javascript/packages/anoncreds-react-native/package.json
wrappers/javascript/packages/anoncreds-shared/package.json
wrappers/python/anoncreds/version.py

update js version

---

wrappers/javascript/packages/anoncreds-react-native/android/cpp-adapter.cpp
wrappers/javascript/packages/anoncreds-react-native/cpp/HostObject.cpp
wrappers/javascript/packages/anoncreds-react-native/cpp/HostObject.h
wrappers/javascript/packages/anoncreds-react-native/cpp/anoncreds.cpp
wrappers/javascript/packages/anoncreds-react-native/cpp/anoncreds.h
wrappers/javascript/packages/anoncreds-react-native/cpp/turboModuleUtility.cpp
wrappers/javascript/packages/anoncreds-react-native/cpp/turboModuleUtility.h
wrappers/javascript/packages/anoncreds-react-native/ios/Anoncreds.mm

fix(js): use quotes instead of brackets for local dependencies

---

Cargo.toml
wrappers/javascript/lerna.json
wrappers/javascript/packages/anoncreds-nodejs/package.json
wrappers/javascript/packages/anoncreds-nodejs/scripts/install.js
wrappers/javascript/packages/anoncreds-react-native/package.json
wrappers/javascript/packages/anoncreds-shared/package.json
wrappers/python/anoncreds/version.py

- fix(js): use universal for darwin nodejs
- chore: update version

use universal for darwin

---

.github/workflows/build.yml

To make it the same as Aries Askar

ci: allow to publish wrappers separately

---

Cargo.lock.android
Cargo.toml
wrappers/javascript/lerna.json
wrappers/javascript/packages/anoncreds-nodejs/package.json
wrappers/javascript/packages/anoncreds-react-native/package.json
wrappers/javascript/packages/anoncreds-shared/package.json
wrappers/python/anoncreds/version.py

Update version to dev.8 so we can release the following PRs:
- #310 
- #309

chore: update version to 0.2.0-dev.8

---

Cargo.lock.android
Cargo.toml
wrappers/javascript/lerna.json
wrappers/javascript/packages/anoncreds-nodejs/package.json
wrappers/javascript/packages/anoncreds-react-native/package.json
wrappers/javascript/packages/anoncreds-shared/package.json
wrappers/python/anoncreds/version.py

Signed-off-by: Stephen Curran <swcurran@gmail.com>

0.2.0-dev.9

---

Cargo.lock.android
Cargo.toml
wrappers/javascript/lerna.json
wrappers/javascript/packages/anoncreds-nodejs/package.json
wrappers/javascript/packages/anoncreds-react-native/package.json
wrappers/javascript/packages/anoncreds-shared/package.json
wrappers/python/anoncreds/version.py

Let's hope it's the last alpha release we need :)

chore: update version to 0.2.0-dev.10

---

README.md

Signed-off-by: Berend Sliedrecht <sliedrecht@berend.io>

mark Python wrapper as not under construction anymore

---

wrappers/javascript/packages/anoncreds-react-native/anoncreds.podspec

Same update as was done in Aries Askar: https://github.com/hyperledger/aries-askar/pull/308

feat: support react-native 0.75

---

.github/workflows/scorcard.yml

Signed-off-by: Stephen Curran <swcurran@gmail.com>

Add OpenSSF Scorecard to repo

---

.github/workflows/build.yml

Signed-off-by: Berend Sliedrecht <berend@animo.id>

build: install correct cross version for android
